### PR TITLE
CI support, version bump

### PR DESCRIPTION
**Pull request by nickmerwin**

### CODE REVIEW

**Comment by nickmerwin** [comment]
@mhartl let's Squash and Merge to consolidate the flood of test commits.

**Comment by ivanistheone** [comment]
Wow @nickmerwin this is awesome.

Long time fan of softcover and very happy to see this PR that explicitly details all the system prerequisites. This paves the way to getting softcover to work inside a docker container too.

**Comment by nickmerwin** [comment]
@ivanistheone thanks! It's been a long time coming. I'm planning on getting a Docker image out soon to cut down on CircleCI build time; currently takes ~10mins just installing dependencies.

I'll let you know when that's live. Cheers!

**Comment by nickmerwin** [comment]
@ivanistheone here's the shiny new Docker image:

https://hub.docker.com/repository/docker/softcover/softcover

**Pull request merged**
